services:
  api:
    build: .
    container_name: brevly_api
    restart: always
    ports:
      - "3333:3333"
    env_file:
      - .env
    environment:
      - POSTGRES_HOST=db
      - NODE_ENV=production
    depends_on:
      db:
        condition: service_healthy
    networks:
      - brevly_network

  db:
    image: postgres:16-alpine
    container_name: brevly_db
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - brevly_pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - brevly_network

networks:
  brevly_network:
    driver: bridge

volumes:
  brevly_pg_data:
